addnote/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'addnote'

urlpatterns = [
    path('', views.index, name='index'),
    path('saveNote/', views.saveNote, name='savenote'),
    path('saveNote/<int:note_id>/', views.result, name='result'),
    path('saveNote/<int:note_id>/vis/', views.view_network, name='vis'),
    path('editnote/<int:note_id>/', views.addnote_save, name='addnote_save'),
    path('delete/<int:note_id>/', views.delete_note, name='delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='home'),
    path('manual/', views.manual, name='manual'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

miraclenote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('mynote/', include('mynote.urls')),
    path('mypage/', include('mypage.urls')),
    path('addnote/', include('addnote.urls')),
]

addnote/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    sttText = models.TextField()
    note_description = models.TextField()
    reg_date = models.DateTimeField()
    audio = models.ImageField(upload_to="audio")
    vis_js_nodes = models.TextField()
    vis_js_edges = models.TextField()

class NoteCnt(models.Model):
    save_cnt = models.IntegerField(default=0)
    input_date = models.IntegerField(default=0)

addnote/forms.py
from django import forms
from addnote.models import Note

class NoteEditForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['subject', 'sttText', 'note_description']

addnote/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.utils.dateformat import DateFormat
from django.http import Http404
from .models import Note
from .models import NoteCnt
from .forms import NoteEditForm
from django.contrib import messages

from addnote import textrank_word2vec
from django.http import JsonResponse
from django.urls import reverse
import librosa
import soundfile as sf
import ast
import urllib3
import json
import base64

from datetime import datetime
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='common:login')
def index(request):
    return render(request, 'addnote/making_note.html')

@login_required(login_url='common:login')
def saveNote(request):
    today = DateFormat(datetime.now()).format('Ymd')    
    noteCnt = NoteCnt.objects.filter(input_date=today)
    
    if noteCnt:
        totalCnt = NoteCnt.objects.get(input_date = today).save_cnt
        if totalCnt > 1000 :
            messages.error(request, "일일 API 사용량이 초과하여 노트 등록이 불가능합니다.")
            return redirect('mynote:index')
    
    user_input_str = request.POST['file_route']
    note = Note()
    note.user = request.user
    note.subject = request.POST['subject']
    note.note_description = request.POST['note_description']
    note.reg_date=timezone.now()
    note.audio = request.FILES['audio']
    note.save()

    apiCallCnt = 0
    sr = 16000
    y, sr = librosa.load('./media/audio/'+user_input_str, sr=sr)
    audioLen = round(len(y)/sr)
    strResult = ""

    if audioLen < 60:
        audioFilePath = './media/audio/'+user_input_str
        strResult = strResult + callEtriApi(audioFilePath)
        apiCallCnt = apiCallCnt + 1
    else:
        for i in range(0, audioLen, 10):
            file_name = str(datetime.now().microsecond)
            ny = y[sr*i:sr*(i+10)]
            sf.write('./media/result/'+file_name+'.wav', ny, sr, format='WAV', endian='LITTLE', subtype='PCM_16') # 깨지지 않음

            audioFilePath = './media/result/'+file_name+'.wav'
            strResult = strResult + callEtriApi(audioFilePath)
            apiCallCnt = apiCallCnt + 1
            
    n = Note.objects.get(id=note.id)
    n.sttText = strResult
    n.save()
    note_id = n.id
    
    if noteCnt :
        cnt = NoteCnt.objects.get(input_date = today)
        cnt.save_cnt = cnt.save_cnt+apiCallCnt
        cnt.save()
    else :
        cnt = NoteCnt()
        cnt.input_date = today
        cnt.save_cnt = apiCallCnt
        cnt.save()
    
    return redirect('addnote:result', note_id=note_id)

@login_required(login_url='common:login')
def result(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.user.id != note.user_id:
        raise Http404("Note does not exist.")
    else:
        form = NoteEditForm(instance=note)
        context = {'note' : note, 'form' : form}
        return render(request, 'addnote/mynote_detail.html', context)


@login_required(login_url='common:login')
def view_network(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if (note.vis_js_nodes == '' or note.vis_js_nodes is None) and (note.vis_js_edges == '' or note.vis_js_edges is None):
        text = note.sttText
        nodes_request, edges_request = textrank_word2vec.textrank_w2v_to_vis(text)
        note.vis_js_nodes = nodes_request
        note.vis_js_edges = edges_request
        note.save()
    else:
        nodes_request, edges_request = ast.literal_eval(note.vis_js_nodes), ast.literal_eval(note.vis_js_edges)
    context = {'result': 'success', 'nodes':nodes_request, 'edges':edges_request}
    return JsonResponse(context)

@login_required(login_url='common:login')
def addnote_save(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    if request.method == "POST":
        form = NoteEditForm(request.POST, instance=note)
        if form.is_valid():
            note = form.save(commit=False)
            note.vis_js_nodes, note.vis_js_edges = textrank_word2vec.textrank_w2v_to_vis(note.sttText)
            note.save()
            return redirect('mynote:index')
    else:
        form = NoteEditForm(instance=note)
        context = {'note' : note, 'form' : form}
    return HttpResponseRedirect(reverse('addnote:result'), args=note.id)

@login_required(login_url='common:login')
def delete_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    note.delete()
    return redirect('mynote:index')

def callEtriApi(audioFilePath):
    openApiURL = "http://aiopen.etri.re.kr:8000/WiseASR/Recognition"
    accessKey = "b1a210f3-f6fd-4fab-8819-0e47149b2a92"
    languageCode = "korean"
    strResult = ""
    
    file = open(audioFilePath, "rb")
    audioContents = base64.b64encode(file.read()).decode("utf8")
    file.close()

    requestJson = {
        "access_key": accessKey,
        "argument": {
            "language_code": languageCode,
            "audio": audioContents
        }
    }

    http = urllib3.PoolManager()
    response = http.request(
        "POST",
        openApiURL,
        headers={"Content-Type": "application/json; charset=UTF-8"},
        body=json.dumps(requestJson)
    )
    try:
        jsonObject = json.loads(str(response.data,"utf-8"))
        strResult = str(jsonObject.get("return_object").get("recognized"))
    except:
        pass

    return strResult

templates/addnote/making_note.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>MiracleNote</title>
    <style>
        #all {
            width: 90%;
            height: 800px;
            position:absolute;
            text-align: center;
            opacity: 78%;
            display: none;
            background-color: white;
            z-index: 1;
        }

    </style>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-1.8.0.js" integrity="sha256-00Fh8tkPAe+EmVaHFpD+HovxWk7b97qwqVi7nLvjdgs=" crossorigin="anonymous"></script>

</head>
<body id="body-pd" style="background-color: #f8f9fa;">
<!-- 좌측에 파란색 바 넣을 코드 -->
{% include "navbar.html" %}
<div id="all">
    <img id="loading" src="{% static 'spinner.gif' %}" style="width:100px; opacity: 100%;height:100px;margin-top:300px"/>
</div>
<div style="position: relative;">
    <!-- Page header with logo and tagline-->
    <header class="py-5 bg-light border-bottom mb-4">
        <div class="container">
            <div class="text-center my-5">
                <h1 class="fw-bolder">여러분만의 특별한 노트를 만들어보세요</h1>
                <p class="lead mb-0">MiracleNote와 함께하세요</p>
            </div>
        </div>
    </header>
    <!-- Search widget-->
    <div class="wrapper">
        <div class="box">
            <form method = "POST" action = "{% url 'addnote:savenote' %}" id="frm" enctype="multipart/form-data">
                {% csrf_token%}
                {% include "form_errors.html" %}
                <div class="card-header">노트명</div>
                <input class="form-control" type="text" id = "subject" name = "subject" placeholder="노트명을 입력하세요" aria-label="노트명을 입력하세요" aria-describedby="button-search" />
                <div class="card-body">
                    <div class="card-header">노트설명</div>
                    <div class="input-group">
                        <textarea name = "note_description" id = "note_description" rows = "7" cols = "40" wrap = "virtual" placeholder="원하는 내용을 입력해 주세요"></textarea>
                        <div class="card mb-10">
                            <div class="col-lg-8">
                                <div class="card-body">
                                    <p class="card-text">wav 확장자 지원</p>
                                    <input type="hidden" id="file_route" name="file_route"/>
                                    <input type = "file" id = "audio" name = "audio" size = "12" onchange="setThumbnail(event);">

                                    <div class="container">
                                        <div class="row">
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                    <button class="btn btn-primary" id="button-search" type="button"  onclick="javascript:doFunction();">노트생성 </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- IONICONS -->
<script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
<!-- JS -->
<script src="{% static 'js/main.js' %}"></script>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
<script>
    window.onload = function(){
        var nav = document.getElementById( 'nav_addnote' );
        nav.classList.add('active');
    }
    function setThumbnail(event) {
        var fileName = document.getElementById('audio').files[0].name;

        var pattern_spc = /[~!@#$%^&*()_+|<>?:;={}]/;

        if( pattern_spc.test(fileName)) {

            alert("file 명에 특수문자 입력은 불가능합니다.");
            $("#audio").val("");
            return;
        }

        fileName = fileName.slice(fileName.indexOf(".") + 1).toLowerCase();

        if(fileName != "wav"){
            alert("wav 파일만 등록 가능합니다.");
            $("#audio").val("");
            return;
        }

        document.getElementById('file_route').value=document.getElementById('audio').files[0].name;
    }
    function doFunction(){
        document.getElementById("all").style.display = "block";
        document.getElementById("frm").submit();
    }
</script>

</body>
</html>