common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='home'),
    path('manual/', views.manual, name='manual'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

miraclenote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('mynote/', include('mynote.urls')),
    path('mypage/', include('mypage.urls')),
    path('addnote/', include('addnote.urls')),
]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    name = forms.CharField(max_length=20)
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "name", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm
from django.views.decorators.clickjacking import xframe_options_exempt

def index(request):
    cur_user = request.user
    if cur_user.is_authenticated:
        return redirect('mynote:index')
    else:
        return render(request, 'common/home.html')

def manual(request):
    return render(request, 'common/manual.html')

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MiracleNote</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">MiracleNote</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">MiracleNote</h1>
                            <p class="lead text-white-50 mb-4">아직도 회의 녹음 따로, 회의록 작성 따로 하시나요? <br />AI기술과 브레인스토밍으로 도와드릴게요</p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                                <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'common:manual' %}">메뉴얼</a>
                                <a class="btn btn-outline-light btn-lg px-4" href="{% url 'common:login' %}">사용하기</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        </section>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; MiracleNote 2021</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MiracleNote</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css">
</head>

<body>
<div class="login-box showed">
    <div class="hide-login-btn">
        <i class="fas fa-times"></i>
    </div>
    <div class="container my-3">
        <form method="post" class="login-form" action="{% url 'common:login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <h1>Welcome</h1>
            <div class="form-group">
                <input class="txtb" type="text" name="username" placeholder="Username" value="{{ form.username.value|default_if_none:'' }}" style="margin:0 auto">
            </div>
            <div class="form-group">
                <input class="txtb" type="password" name="password" placeholder="Password" value="{{ form.password.value|default_if_none:'' }}" style="margin:0 auto">
            </div>
            <button type="submit" class="login-btn">로그인</button>
            <br /><br><button type="button" class="login-btn" onclick="location.href='{% url 'common:signup' %}'">회원가입</button>
        </form>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/common/manual.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>MiracleNote</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    </head>
    <body style="padding:0">
        <!-- 좌측에 파란색 바 넣을 코드 --> 
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="/">MiracleNote</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" aria-current="page" href="/">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">미라클 노트 사용방법!</h1>
                    <p class="lead mb-0">MiracleNote와 함께하세요</p>
            </div>
        </header>
            <div class="box" style="text-align:center; margin-left:-350px">
                <!--static 폴더에 maunal.pdf 파일 업로드 , 해당 경로에 따라 src 경로 수정-->
                <object type="application/pdf" data="{% static 'manual.pdf' %}#toolbar=0" height="800" width="800">
                    <embed type="application/pdf" src="{% static 'manual.pdf' %}#toolbar=0" height="800" width="800"/>
                </object>
            </div>
    </body>


</html>

        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script> 
    </body>
</html>

templates/common/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>MiracleNote</title>
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" media="screen" title="no title" charset="utf-8">
</head>
<body>
<div class="login-box showed">
    <article class="container my-3">
        <div class="page-header">
            <h1 style="font-weight: bolder;">회원가입 <small style="color:#373b3e">Sign up</small></h1>
        </div> <br />
        <div class="sector">
            <form method="post" action="{% url 'common:signup' %}">
                {% csrf_token %}
                {% include "form_errors.html" %}
                <h3 style="font-weight: bolder;">계정 생성</h3> <br />
                <div class="form-group">
                    <label for="username">아이디</label>
                    <input type="text" class="form-control" name="username" id="username" placeholder="아이디" value="{{ form.username.value|default_if_none:'' }}">
                </div>

                <div class="form-group">
                    <label for="password1">비밀번호</label>
                    <input type="password" class="form-control" name="password1" id="Password" placeholder="비밀번호" value="{{ form.password1.value|default_if_none:'' }}">
                </div>

                <div class="form-group">
                    <label for="password2">비밀번호 확인</label>
                    <input type="password" class="form-control" name="password2" id="Password2" placeholder="비밀번호 확인" value="{{ form.password2.value|default_if_none:'' }}">
                    <p class="help-block" style="color:#373b3e">비밀번호 확인을 위해 다시 한번 입력 해 주세요</p>
                </div><br />
                <h3 style="font-weight: bolder;">개인 정보</h3> <br />
                <div class="form-group">
                    <label for="name">이름</label>
                    <input type="text" class="form-control" name="name" id="Name" placeholder="이름을 입력해 주세요" value="{{ form.name.value|default_if_none:'' }}">
                </div>

                <div class="form-group">
                    <label for="email">이메일 주소</label>
                    <input type="text" class="form-control" name="email" id="Email" placeholder="이메일 주소를 입력해 주세요" value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <br />
                <div class="form-group text-center">
                    <button type="submit" class="btn btn-lg btn-primary">회원가입</button>
                    <button type="button" class="btn btn-secondary btn-lg" onclick="location.href = '{% url 'common:home' %}'">가입 취소</button>
                </div>
            </form>
        </div>
    </article>

    <style>
        .full {
            background : linear-gradient(45deg, #9fbaa8, #31354c)
        }
    </style>

</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>