addnote/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'addnote'

urlpatterns = [
    path('', views.index, name='index'),
    path('saveNote/', views.saveNote, name='savenote'),
    path('saveNote/<int:note_id>/', views.result, name='result'),
    path('saveNote/<int:note_id>/vis/', views.view_network, name='vis'),
    path('editnote/<int:note_id>/', views.addnote_save, name='addnote_save'),
    path('delete/<int:note_id>/', views.delete_note, name='delete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.index, name='home'),
    path('manual/', views.manual, name='manual'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

miraclenote/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('mynote/', include('mynote.urls')),
    path('mypage/', include('mypage.urls')),
    path('addnote/', include('addnote.urls')),
]

mynote/urls.py
from django.urls import path
from . import views

app_name = 'mynote'

urlpatterns = [
    path('', views.index, name='index'),
]

mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('', views.password_edit_view, name='password_edit'),
    #path('', views.index, name='index'),
]

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/messageShow.html
    {% if message.tags == "error" %}
        <div class="alert alert-danger alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
    {% else %}
        <div class="alert alert-{{message.tags}} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
    {% endif%}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>

templates/navbar.html
<div class="l-navbar" id="navbar">
    <nav class="nav">
        <div>
            <div class="nav__brand">
                <ion-icon name="menu-outline" class="nav__toggle" id="nav-toggle"></ion-icon>
                <h5> <a href="{% url 'common:home' %}" class="nav__logo">Miraclenote</a></h5>
            </div>
            <div class="nav__list">
                <a href="{% url 'mynote:index' %}" id = "nav_index" class="nav__link">
                    <ion-icon name="home-outline" class="nav__icon"></ion-icon>
                    <span class="nav_name">Dashboard</span>
                </a>
                <!--추후 share 추가-->
                <!--
                <div href="#" class="nav__link collapse">
                    <ion-icon name="folder-outline" class="nav__icon"></ion-icon>
                    <span class="nav_name">Mynotes</span>
                </div>-->

                <a href="{% url 'addnote:index' %}" id = "nav_addnote" class="nav__link">
                    <ion-icon name="pie-chart-outline" class="nav__icon"></ion-icon>
                    <span class="nav_name">Analytics</span>
                </a>

                <a href="{% url 'mypage:password_edit' %}" id = "nav_mypage" class="nav__link">
                    <ion-icon name="settings-outline" class="nav__icon"></ion-icon>
                    <span class="nav_name">Settings</span>
                </a>
            </div>
            {% if user.is_authenticated %}
            <a href="{% url 'common:logout' %}" class="nav__link">
                <ion-icon name="log-out-outline" class="nav__icon"></ion-icon>
                <span class="nav_name">Log out</span>
            </a>
            {% endif %}
        </div>
    </nav>
</div>